# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jeFsI299O8KA0X-L1HyN3-zhlRpL5fKA
"""

import streamlit as st
import joblib
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

st.title("ML Classification App - Breast Cancer")

uploaded_file = st.file_uploader("Upload Test CSV", type=["csv"])

model_option = st.selectbox(
    "Select Model",
    ["LogisticRegression", "DecisionTree", "KNN",
     "NaiveBayes", "RandomForest", "XGBoost"]
)

if uploaded_file is not None:
    data = pd.read_csv(uploaded_file)

    # Load scaler
    scaler = joblib.load("model/scaler.pkl")

    # Separate target if exists
    if "target" in data.columns:
        y_true = data["target"]
        X = data.drop("target", axis=1)
    else:
        X = data
        y_true = None

    # Scale features
    X_scaled = scaler.transform(X)

    # Load model
    model = joblib.load(f"model/{model_option}.pkl")

    # Predict
    predictions = model.predict(X_scaled)

    st.write("Predictions:")
    st.write(predictions)

    # Show confusion matrix if target available
    if y_true is not None:
        st.subheader("Confusion Matrix")
        cm = confusion_matrix(y_true, predictions)

        fig, ax = plt.subplots()
        ax.matshow(cm)
        plt.xlabel("Predicted")
        plt.ylabel("Actual")
        st.pyplot(fig)

    st.success("Prediction Completed")



