# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jeFsI299O8KA0X-L1HyN3-zhlRpL5fKA
"""

!pip install streamlit

import streamlit as st
import joblib
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

st.title("ML Classification App - Breast Cancer")

uploaded_file = st.file_uploader("Upload Test CSV", type=["csv"])

model_option = st.selectbox(
    "Select Model",
    ["LogisticRegression", "DecisionTree", "KNN",
     "NaiveBayes", "RandomForest", "XGBoost"]
)

if uploaded_file is not None:
    data = pd.read_csv(uploaded_file)

    model = joblib.load(f"model/{model_option}.pkl")

    predictions = model.predict(data)

    st.write("Predictions:")
    st.write(predictions)

    st.success("Prediction Completed")



import streamlit as st
import pandas as pd
import joblib
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, classification_report

st.title("Breast Cancer Classification App")

st.write("Upload test dataset to make predictions")

uploaded_file = st.file_uploader("Upload CSV file", type=["csv"])

model_option = st.selectbox(
    "Select Model",
    ["LogisticRegression", "DecisionTree", "KNN",
     "NaiveBayes", "RandomForest", "XGBoost"]
)

if uploaded_file is not None:
    data = pd.read_csv(uploaded_file)

    model = joblib.load(f"model/{model_option}.pkl")

    predictions = model.predict(data)

    st.write("Predictions:")
    st.write(predictions)

    st.subheader("Confusion Matrix")

    if "target" in data.columns:
        y_true = data["target"]
        cm = confusion_matrix(y_true, predictions)

        fig, ax = plt.subplots()
        ax.matshow(cm)
        plt.xlabel("Predicted")
        plt.ylabel("Actual")
        st.pyplot(fig)

    st.success("Prediction Completed")

